version: "3.7"
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mongo:3.4.21-xenial
    deploy:
      restart_policy:
        condition: always
    ports:
      - "27017:27017"
